const emojiList = [
    ':face_with_cowboy_hat:',
    ':muscle:',
    ':sunglasses:',
    ':heart_eyes:',
    ':unicorn_face:',
    ':female_genie:',
    ':monkey_face:',
    ':hugging_face:',
    ':kissing_heart:',
    ':nerd_face:',
    ':panda_face:',
    ':man_dancing:',
    ':dancer:',
    ':heart:',
    ':male_mage:',
    ':mage:',
    ':zany_face:',
    ':blush:',
    ':innocent:',
    ':ghost:',
    ':male-singer:',
    ':man-gesturing-ok:',
    ':ok_woman:',
    ':female-singer:',
    ':mermaid:',
    ':merman:',
    ':smirk_cat:',
    ':star-struck:',
    ':parrot:',
    ':open_mouth:',
    ':man-tipping-hand:',
    ':woman-tipping-hand:',
    ':kissing_cat:',
    ':the_horns:',
    ':spock-hand: ',
    ':punch:',
    ':relaxed:',
    ':t-rex:',
    ':heart-eyes:',
    ':stuck_out_tongue_winking_eye:',
    ':smirk:',
    ':laughing:',
    ':relieved:',
    ':male-cook:',
    ':female-cook:',
    ':fox_face:',
    ':lion_face:',
    ':tiger:',
    ':male-technologist:',
    ':female-technologist:',
    ':female_elf:',
    ':elf:',
    ':partyface:',
    ':catdance:',
    ':charmander_dancing:',
    ':love:',
    ':meow_popcorn:',
    ':meow_coffee:',
    ':meow_party:',
    ':blush-gif:',
    ':dabbing:',
    ':daenery:',
    ':nightking:',
    ':arya:',
    ':tyrionl:',
    ':johnsnow:',
    ':bran-the-broken:',
    ':cersei:',
    ':jaimel:',
    ':greyworm:',
    ':perfect:',
    ':bongo_blob:',
    ':blob-yes:',
    ':blob_excited:',
    ':blob-sunglasses:',
    ':snap-point:',
    ':agree:',
    ':drop-the-mic:',
    ':pikachu_wave:',
    ':poke_pika_wink:',
    ':poke-pika-angry:',
    ':attitude-monkey:',
    ':love-monkey:',
    ':monkey_dance:',
    ':attitude-monkey:',
    ':bigsmile:',
    ':emo:',
    ':fb-like:',
    ':aggretsuko_paperwork:',
    ':pig-happy-jumping:',
    ':danceydoge:',
    ':bruce:',
    ':cookie_monster:',
    ':batman:',
    ':one-sec-cooking:',
    ':kids:',
    ':hammer_time:',
];

const getRandomEmojis = (numberRequested) => {
    const randomEmojis = [];
    const emojis = emojiList;

    while (numberRequested !== randomEmojis.length) {
        if (emojis.length === 0) {
            randomEmojis.forEach((emoji) => {
                emojis.push(emoji);
            });
        }
        const randomIndex = Math.floor(Math.random() * emojis.length);
        randomEmojis.push(emojis[randomIndex]);
        emojis.splice(randomIndex, 1);
    }

    return randomEmojis;
};

module.exports = getRandomEmojis;
